### ISSUE TITLE
Finnmaid-GETM

### ISSUE THREAD

**Issue by jens-daniel-mueller** [jens-daniel-mueller/Baltic_Productivity#1]
This issue collects all conversations adressing the handling, merging and integrated assesment of obervational data from VOS Finnmaid and GETM model results.

**Comment by jens-daniel-mueller** [comment]
Email request from Lara (translated from german with google translator):

Moin Jens,
Thank you! Then I'll get used to it.

I probably will not just work in the .Rmd file. This makes a lot more difficult, especially when it comes to loading and saving data, which is the main problem. But I will transfer everything as well as possible and as soon as possible directly into the .Rmd format.

Yesterday I worked on programming a workflow that goes through the files in a loop and performs the necessary tasks.

There were two questions:
1) For which individual periods should the analysis be calculated? Per year? Or in the end everything even in the same picture?
2) The GETM data should be compared with the Finnmaid data, presumably with the "standard tracks"? These are currently only for 2019, right? Is there a script or workflow that I can count on for the other years or are you doing that?
3) The following files can not be opened:
"20060201 / Finnmaid.E.2d.nc" (2)
"20060301 / Finnmaid.E.2d.nc" (3)
"20060401 / Finnmaid.E.2d.nc" (4)
"20060501 / Finnmaid.E.2d.nc" (5)
"20060601 / Finnmaid.E.2d.nc" (6)

For all other GETM data I've already written out the necessary variables and saved them in a file every month. So as soon as I know which time frames are to be displayed and how it works with the standard tracks, I can continue.

Greetings and you three have a nice weekend!
Lara

**Comment by jens-daniel-mueller** [comment]
Hi Lara,

**workflow:**
I do not really see the advantage to start coding in a different Script. Code in the .Rmd file can be executed chunk wise (which results for example in objects being permanently loaded to the environment, what does not happen if you run the whole .Rmd file) and is therefore even better structured than in a regular .R Script. Anyways, organize your work as you feel it's best for you!

**First tasks**

- The idea is indeed to compare the sea surface temperature (SST) determined by Finnmaid and GETM for the entire period (2006-2019).
- as a first approach, we want to restrict that comparison to route "E" and to the mean daily SST observed in the subregion "4. EGS" (Lat>57.5 & Lat<58.5)
- Therefore, please calculate mean daily values for GETM SST for each day and mean values for each crossing of Finnmaid (ID) first, and than merge obervations from all years into one file.
- Then we need two types of plots (ideally coded as dygraphs and synchronized to each other):
1. A timeseries showing all daily mean SST values from both GETM and Finnmaid, ideally including some indication of variability (e.g. errorbars or ribbon showing SD, min/max or similar)
2. A timeseries showing the SST differences between Finnmaid and GETM for days where Finnmaid observations are available.

All data you're using right now should already be referenced to the standard track. The filename "FM_all_2019_on_standard_tracks.nc" just indicates it contains data until 2019.

I've no idea why you can't open the files. There are several netcdf viewers available, for example here:
https://www.giss.nasa.gov/tools/panoply/
Can you please check, whether you can open with those?
Also, you should use a viewer to check if your R read-in procedure worked correctly.
If problems with those files should persist, please contact ulf graewe by mail an Cc me.

**Outlook:**
-After comparing SST estimates in subregion EGS we want to extend that to the entire Finnmaid transect, meaning: 3 Hovmöller plots (x:time, y:latitude or distance from Travemünde) for Finnmaid SST, GETM SST and delta SST. Maybe you already wanna keep that in mind when coding your subsetting and merging procedures...

Cheers, Jens

**Comment by LSBurchardt** [comment]
Dygraphs as interactive shiny plots?

**Comment by jens-daniel-mueller** [comment]
- [ ] do this

**Comment by jens-daniel-mueller** [comment]
Hi Lara,

first version of the merged Finnmaid-GETM data looks good. I modified it a bit, compiled the html and pushed, so it's online now.

Main changes I did:

- included global chunk options (l.11)
- removing some code chunks not required
- Cleaning the descriptive texts
- compiling and saving all GETM data in one file rather than individual files for each month
- summarized GETM data are now stored in "data/_summarized_data_files"
- ggplot was changed to an interactive dygraphs timeseries plot

Next task, ordered by priority:

- [x] update folder structure in "data" on your machine and bring recent Rmd-file to work
- [x] revise Finnmaid data read-in: timeseries_mean (l.176 ff) does not work because in the for loop (l. 153 ff) mean values are already calculated. include calculation of min, max, sd in the for loop.
- [x] check whether package tidync (https://ropensci.org/blog/2019/11/05/tidync/) includes functionality that makes our life easier. If yes, please implement.
- [x] safe the summarized Finnmaid data to a csv-file, similar to the GETM results
- [ ] try to harmonize object, column and file names for Finnmaid and GETM data
- [x] safe the merged Finnmaid-GETM data in a new folder "data/_merged_data_files"
- [x]  Create a second dygraph timeseries plot showing the SST differences between Finnmaid and GETM for days where Finnmaid observations are available. The SST and the delta SST timeseries should be synchronized. See here: https://rstudio.github.io/dygraphs/gallery-synchronization.html
- [ ] include some indication of variability (e.g. errorbars or ribbon showing SD, min/max or similar) in the dygraph. See here: https://rstudio.github.io/dygraphs/gallery-upper-lower-bars.html. CAVEAT: The Finnmaid timeseries is discontinous in the created timeseries object (xts), due to the high temporal resolution of the GETM data. I guess this is why Finnmaid data are shown only as points, not connected by lines. If this is a problem for the the ribbon, let it be.

Hau rein ;-)

**Comment by LSBurchardt** [comment]
I have a question on the merged dataset of Finnmaid and GETm data.
There exist different possibilities to combine them, the question is, what kind of merge/join we want and need.

I am right now combining them by date, since that is the comparison we want to make.

Now, do we want to keep **only** the dates, that we have values for from both datasets?
Do we want to keep **all** dates and just have an NA when there is not data for both?
Do we want to keep **all Finnmaid** dates?

Depending on the answer I will need to merge them in a different way.

**Comment by jens-daniel-mueller** [comment]
For the delta SST timeseries plot we only need dates when Finnmaid SST is available (but for the plots of absolute SST values of GETM and Finnmaid, keep the full temporal resolution of GETM). How you organize the data set (NA's: yes or no) is up to you.

As an outlook: for the Hovmoeller plot of delta SST (color) vs time (x) and distance to Travemünde (y), we want to take the time of the day into account, to achieve the best match between Finnmaid and GETM data. So, you will need to identify the GETM output values that are closest to the Finnmaid observation.

**Comment by jens-daniel-mueller** [comment]
Very good progress Lara.

I revised the latest version (c19981f).
Major changes I did:
- set chunks not required to knit html to "eval=FALSE"
- modified the dygraphs, in particular defining connected dots by " connectSeparatedPoints=TRUE"

Before you continue with the Hovmoeller plots, please revise the object and variable names (I unticked the task above). For example `SST_GETM_mean` is meaningful, wherease other names such as 
`timeseries`, `comparison`, and `value.y` will make it hard for me to read the code in a few weeks to months from now.

**Comment by LSBurchardt** [comment]
I am currently preparing the data for the Hovmöller Plots. 
We decided to want to match values by time and ignore the difference in water depths for now. 

To match the dates is more tedious than expected, there is no clear function or set of functions to do it, all I found look like they will be far to slow for more than 21 million entries, which we would have for 544 coordinate points * 248 timesteps per month and ~150 months of data. 
Furthermore, the matching I tried out on a subset did not work as indicated and was not helpful for the task we want to achieve.

How to proceed? Try further or switch to matching with depth with day means instead to get the Hovmöller plots working first and then try the matching again?

**Comment by jens-daniel-mueller** [comment]
**For know:** it's fine to use the GETM daily mean temp values, extracted from the 3d datafiles (water depth 2-4m). Merge those with Finnmaid observations by mean dates (neglecting the actual sampling time in the Finnmaid data set).

**Alternative:** if you would like to achieve merging Finnmaid and high-resolution 2d GETM data, this approach might work:
1. create a data set with all GETM 2d data (3 columns: date_time, lat_interval, GETM_SST)
2. create a data set with all Finnmaid data (3 columns: date_time, lat_interval, Finnmaid_SST)
3. merge both data sets by date_time and lat_interval
4. raster date_time into 3h intervals
5. group by date_time_interval and lat_interval and calculate mean Finnmaid_SST and GETM_SST
6. remove columns where Finnmaid_SST_mean is NA
7. calculate delta_SST as Finnmaid_SST - GETM_SST

**Outlook:** We will later need to merge mixing depth from GETM 2d files with Finnmaid observations across all latitudes. The mixing depth parameter is not stored in the 3d files. It will be OK to reduce the temporal resolution of the 2d files to 1 day for this exercise, but I wanted to let you know, that at some point working with the 2d files will be required.

**Comment by jens-daniel-mueller** [comment]
Changelog addressing my changes (f15ec22) since Laras first version including Hovmoeller plots:

- Switched from inner_join to full_join when merging Finnmaid and GETM data, in order to preserve the full spatio-temporal coverage of GETM
- Included Hovmoeller plots for SST GETM (daily) and Finnmaid (weekly)
- Facetted plots by year
- Restricted plots to years 2007-18
- Changed data set for delta SST plot to one including NA, in order to have full temporal coverage from GETM included and therefore equal date ranges in each year for Hovmoeller plots
- Changed color scale of delta SST to scale_fill_divergent from metR package

**Comment by jens-daniel-mueller** [comment]
Hi Lara,
Excellent job preparing the Hovmoeller plots.
Here are the next tasks we need to tackle:

- [ ] Calculate Finnmaid monthly mean sea surface salinity (SSS) for each distance interval (1:544) over all years and plot SSS vs distance from Travemünde. Include standard deviation of SSS for each distance interval.
- [ ] Switching back to the regionally subsetted data, please produce two synchronized dygraph for:
1. pCO2 timeseries (Finnmaid)
2. mld_age_1, mld_age_3, mld_age_5, mld_rho, mld_tke (additional GETM variables in 2d files)

For this task, you can already merge Finnmaid observations and mld parameters from GETM into one data file, which will be the basis for future calculations.

Let’s schedule a chat before you start with this!

**Comment by jens-daniel-mueller** [comment]
Next tasks to tackle

- [x] Check and implement if helpful:

- Faster read-in of csv files: https://vroom.r-lib.org/
- More elegant slicing of netcdf files: https://docs.ropensci.org/tidync/

- [x] Harmonize and clean naming conventions of files, objects, columns, functions

- [x] Split Rmd’s and website structure into:
- SST
- MLD/pCO2
- SSS
- CT

- [ ] In newly created CT.Rmd
- Use subregions NGS only
- Calculate mean salinity across all measurements made between march - september
- create one single dygraph timeseries plot with two seperate y-axis for MLD5 (GETM) and pCO2 (Finnmaid); see https://rstudio.github.io/dygraphs/gallery-axis-options.html

**Comment by jens-daniel-mueller** [comment]
Closed, because code has been split in separate Rmd files. New issues for the splitted Rmd's are opened when required.
